#!/usr/bin/env bash
# CityLive — portable installer for KDE Plasma 6 (Wayland or X11).
# Copies the wallpaper plugin into place, applies it to every desktop, auto-sizes the
# city to this machine's screen(s), then reloads the shell. Safe to re-run.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/org.citylive.wallpaper"
DEST="$HOME/.local/share/plasma/wallpapers/org.citylive.wallpaper"

if [ ! -d "$SRC" ]; then echo "error: $SRC not found (run this from the CityLive folder)"; exit 1; fi

echo "==> Installing plugin to $DEST"
mkdir -p "$(dirname "$DEST")"
rm -rf "$DEST"
cp -r "$SRC" "$DEST"

# Personal settings: birthdays / location / cycle live in a LOCAL, git-ignored file so they never enter the
# public repo. If it's present, bake it into the INSTALLED wallpaper's localcfg.js (the committed source copy
# stays empty). Edit config.local.json and re-run this script to change your birthdays.
LOCALCFG="$SRC/contents/config.local.json"
if [ -f "$LOCALCFG" ]; then
  if command -v node >/dev/null 2>&1 && node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$LOCALCFG" 2>/dev/null; then
    node -e "const fs=require('fs'); const c=fs.readFileSync(process.argv[1],'utf8'); fs.writeFileSync(process.argv[2], '// GENERATED by install.sh from config.local.json — edit that file, not this one.\nvar CONFIG = '+c+';\n');" "$LOCALCFG" "$DEST/contents/js/localcfg.js"
    echo "==> Applied your personal settings (birthdays/location/cycle) from config.local.json"
  else
    echo "   (config.local.json present but not valid JSON, or node missing — using empty settings)"
  fi
fi

# SINGLE ENGINE: the browser/phone build (phone/) is the SAME engine — keep it in lockstep with the
# canonical wallpaper city.js so it never drifts into a stale fork. (Runs on every OS via any browser.)
for dst in phone/city.js web/city.js desktop/renderer/city.js; do
  if [ -f "$HERE/$dst" ]; then
    cp -f "$SRC/contents/js/city.js" "$HERE/$dst"
    echo "==> Synced $dst from the canonical engine (cross-platform build)"
  fi
done

DB="$(command -v qdbus6 || command -v qdbus || true)"
if [ -n "$DB" ]; then
  echo "==> Setting CityLive as the wallpaper on all desktops + auto-sizing to this machine"
  "$DB" org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
    var ds = desktops();
    for (var i = 0; i < ds.length; i++) {
      var d = ds[i];
      d.wallpaperPlugin = "org.citylive.wallpaper";
      var n = screenCount, tot = 0;
      for (var k = 0; k < n; k++) tot += screenGeometry(k).width;   // total logical width
      d.currentConfigGroup = ["Wallpaper", "org.citylive.wallpaper", "General"];
      d.writeConfig("worldW", tot);   // whole city spans the full desktop
      d.writeConfig("worldX", -1);    // -1 = auto (each screen reads its own virtualX)
    }
  ' || echo "   (couldn't auto-apply via D-Bus — set it manually in System Settings > Wallpaper)"
else
  echo "==> qdbus not found; after this finishes, open System Settings > Wallpaper and pick 'CityLive Pixel City'."
fi

# CityLive Settings launcher — a KDE app-menu shortcut to edit personal settings (birthdays,
# location, day length, which apocalypse ends the world). Complements the right-click wallpaper dialog.
if [ -f "$HERE/citylive-settings" ]; then
  echo "==> Installing the 'CityLive Settings' launcher (find it in your app menu)"
  chmod +x "$HERE/citylive-settings" 2>/dev/null || true
  ICON_DEST="$HOME/.local/share/icons/citylive.png"
  mkdir -p "$(dirname "$ICON_DEST")" "$HOME/.local/share/applications"
  [ -f "$HERE/desktop/build/icon.png" ] && cp -f "$HERE/desktop/build/icon.png" "$ICON_DEST"
  cat > "$HOME/.local/share/applications/citylive-settings.desktop" <<DESK
[Desktop Entry]
Type=Application
Name=CityLive Settings
Comment=Edit your CityLive wallpaper settings (birthdays, location, day length, finale)
Exec=$HERE/citylive-settings
Icon=$ICON_DEST
Terminal=false
Categories=Settings;Utility;
DESK
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
fi

echo "==> Reloading plasmashell"
if command -v systemctl >/dev/null && systemctl --user is-active plasma-plasmashell.service >/dev/null 2>&1; then
  systemctl --user restart plasma-plasmashell.service
else
  kquitapp6 plasmashell 2>/dev/null || true
  sleep 1
  (nohup plasmashell >/dev/null 2>&1 &) || true
fi

echo
echo "Done!  CityLive is installed."
echo "  • If the wallpaper didn't switch, open System Settings > Wallpaper, choose 'CityLive Pixel City'."
echo "  • Location is Norwich CT (day/night, sun, moon, stars, weather). To use YOUR location,"
echo "    right-click the desktop → Configure Desktop and Wallpaper → CityLive → set Location"
echo "    (or keep using config.local.json, as above)."
